Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Style/MethodName:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%q': '[]'
    '%Q': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Metrics/LineLength:
  Max: 99
