Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Style/MethodName:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/VariableName:
  Enabled: false
